# Generated by Django 5.0.6 on 2024-08-14 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='email',
            new_name='email_addres',
        ),
    ]
